# Generated by Django 4.1.6 on 2023-04-25 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppLogic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fechasimportantes',
            old_name='transcripcion_id',
            new_name='transcripcion',
        ),
        migrations.RenameField(
            model_name='mygroups',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='transcripciones',
            old_name='group_id',
            new_name='group',
        ),
    ]
