# Generated by Django 4.1.6 on 2023-04-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLogic', '0002_rename_transcripcion_id_fechasimportantes_transcripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcripciones',
            name='resumen',
            field=models.TextField(null=True),
        ),
    ]
