# Generated by Django 4.1.6 on 2023-04-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLogic', '0006_fechasimportantes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechasimportantes',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
